### ISSUE TITLE
Bug on transfer amount

### ISSUE THREAD

**Issue by Yhtiyar** [G7DAO/contracts#28]
https://github.com/G7DAO/contracts/blob/2c04437633e574ae01b45b16f33694cb4a01b7a3/contracts/inventory/Inventory.sol#L329-L338

Here, the `existingItem.Amount` is transferred to the user, but only `amount` is reduced here:
https://github.com/G7DAO/contracts/blob/2c04437633e574ae01b45b16f33694cb4a01b7a3/contracts/inventory/Inventory.sol#L350

This allows to redeem `ERC1155` tokens more than you deposited.

**Comment by zomglings** [comment]
Acknowledged, great catch @Yhtiyar .

Will push a fix (with a test case) shortly.

Thanks!
