### ISSUE TITLE
Stuck nft

### ISSUE THREAD

**Issue by Yhtiyar** [G7DAO/contracts#31]
It is possible to equip `ERC721` item with amount 0,  but it will be impossible to unequip  this item because of check here (even if you want to enequip all):
https://github.com/G7DAO/contracts/blob/2c04437633e574ae01b45b16f33694cb4a01b7a3/contracts/inventory/Inventory.sol#L322-L328

this check is a good check.

I think it is better to add an another check `amount == 1` in `equip` function for `ERC721` items

**Comment by zomglings** [comment]
Agreed - it is important for amount semantics to be consistent between `equip` and `unequip` methods.

Let me know if you want to make a PR @Yhtiyar , otherwise I can push your proposed fix next week.
